name: Node.js CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci --force
    - name: Lint
      run: npm run lint
    - name: Test
      run: npm run test -- --coverage --verbose --ci
    - name: Build
      run: npm run build
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
